# This pipeline is to build and publish anax binaries
name: anax-images-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events. Run the workflow manually
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    # IMAGE_REPO and DOCKER_REGISTRY required by the MakeFile
    env:
      GOPATH: /home/runner/work/anax/anax/go
      OWNER: open-horizon
      REPO: anax
      IMAGE_REPO: maltekreeti
      DOCKER_REGISTRY: ghcr.io
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Test environment variables
      - name: Echo env variables
        run: echo ${OWNER} && echo ${REPO}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Prepare the environment
      - name: Set up golang 1.17.1
        uses: actions/setup-go@v2
        with:
           go-version: '1.17.1'
      
      # Login to github container registry
      - name: Login to GITHUB container registry
        uses: docker/login-action@v2
        with:
          registry: $DOCKER_REGISTRY
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Checks-out open-horizon/anax repo
      - name: Check-out anax repo
        run: |
          mkdir -p ${GOPATH}/src/github.com/${OWNER}
          cd ${GOPATH}/src/github.com/${OWNER} && git clone https://github.com/${OWNER}/${REPO}.git

      # Build anax binaries
      - name: Build anax binaries
        run: |
          cd ${GOPATH}/src/github.com/${OWNER}/${REPO} && make

      # Build anax docker images
      - name: Build and publish docker images
        run: |
          echo $arch
          cd ${GOPATH}/src/github.com/${OWNER}/${REPO}
          make fss-package
          make anax-package 
          if [ $arch = 'amd64' ]; then
               make agbot-package
          fi
          make anax-k8s-package
         
